program: /Users/yonghuizuo/workspace/projects/handson_rl/mab/main.py
method: grid  # 使用网格搜索替代贝叶斯优化，更快地覆盖关键参数组合
metric:
  name: regret
  goal: minimize
parameters:
  algorithm:
    values: ["epsilon-greedy", "decaying-epsilon-greedy", "ucb", "thompson-sampling"]
  
  # 探索不同的拉杆数量，测试不同问题难度
  k:
    values: [10, 20]  # 减少拉杆数量选项
  
  # 探索不同的步数，测试长期和短期性能
  steps:
    values: [2000, 5000]  # 减少步数，加快执行
  
  # 使用多个随机种子，确保结果的稳定性
  seed:
    values: [1, 5]  # 减少种子数量
  
  # 对于epsilon-greedy，探索关键的epsilon值
  epsilon:
    values: [0.0001, 0.01, 0.1]  # 只测试几个关键值
  
  # 对于UCB，探索不同的系数值
  ucb-coef:
    values: [0.5, 1.0, 1.5]  # 只测试几个关键值
  
  # 在所有实验中使用wandb后端
  backend:
    value: "wandb"
  
  # 项目名称
  project-name:
    value: "mab-sweep-experiments"

# 条件参数：只在特定算法下应用特定参数
# 这里使用wandb的条件语法定义条件参数
conditional_parameters:
  epsilon:
    algorithm: "epsilon-greedy"
  
  ucb-coef:
    algorithm: "ucb"

# 命令行模板，根据参数生成命令
command:
  - python
  - ${program}
  - "--algorithm=$(algorithm)"
  - "--k=$(k)"
  - "--steps=$(steps)"
  - "--seed=$(seed)"
  - "--backend=$(backend)"
  - "--project-name=$(project-name)"

# 指定工作目录
working_directory: /Users/yonghuizuo/workspace/projects/handson_rl/mab
